### ISSUE TITLE
翻译用词对照表

### ISSUE THREAD

**Issue by lazurey** [the-road-to-learn-react/the-road-to-react-chinese#26]
## 统一术语翻译

这里统一术语和用词的翻译讨论贴。

约定：

* 经讨论后无需翻译的标注为 `不翻译`
* 待讨论的请在条目第一列标注 `:question:` (❓)
* 已达成一致请标注 `:white_check_mark:`  （✅ ）

所有和 React 相关的术语，默认参考沿用 [React 中文文档](https://zh-hans.reactjs.org/) 及其 [术语表](https://github.com/reactjs/zh-hans.reactjs.org/issues/2)；如有不适用的情况，请在此讨论

| 定稿 | 原文        | 中文           | 备注  |
| ----- | ----- | ---------- | ----- |
| :white_check_mark: | hook | `不翻译`  | 参考 React 中文文档 |
| :white_check_mark: | reducer | `不翻译`  | 参考 React 中文文档 |
| ❓| local storage | 本地存储 | 非`localStorage` 或 `LocalStorage`， 是否需要翻译 |
| ❓ | handler | 处理函数  |  |
| :white_check_mark: | prop / props | `不翻译`  |  React 文档这样建议，以避免和 attribute 混淆 |
| :white_check_mark: | attribute | 属性  | |
| ❓ | stories | 不翻译  | |
| :white_check_mark:| Xxx component | Xxx 组件| 不翻译组件名，方便代码对应，例如 Search component 翻译为 Search 组件|
| ❓ | state updater | state 更新函数 | or 更新器？ |
| :white_check_mark:| block body | 块体 | 箭头函数的概念，在 React 文档中没有找到对照，参考了MDN中文文档 |
| :white_check_mark:| concise body | 简写体 | 箭头函数的概念，在 React 文档中没有找到对照，参考了MDN中文文档 |
| :white_check_mark:| state | `不翻译` | 参考 React 中文文档 |

### 每节练习的前两个item翻译
原文
```
* Confirm your [source code for the last section](some_link_here).
* Confirm the [changes from the last section](some_link_here).
```

可统一翻译为：
```markdown
* 检查[上一节的源码](remember to update link)。
* 确认[上一节之后的变更](remember to update link)。
```

## Commit message
更新  Update
修复  Fix
翻译  Trans

例如：`[Trans][#issue_number] your message here`

**Comment by lazurey** [comment]
关于 `hook` 的翻译，和 React 中文文档保持一致，保留原文不翻译。
https://zh-hans.reactjs.org/docs/hooks-intro.html

**Comment by mengyaolin** [comment]
某些练习中的参考资料：Read more about [xxx].
可统一翻译为：阅读更多关于 [xxx]

**Comment by mengyaolin** [comment]
文章标题中的（Advanced）统一翻译成（高级）
