### ISSUE TITLE
react-modern - Third-Party Libraries in React

### ISSUE THREAD

**Issue by LiJiahaoCoder** [the-road-to-learn-react/the-road-to-react-chinese#34]

**Comment by dcZhangTW** [comment]
这个翻译的提交貌似被回滚掉了 @LiJiahaoCoder

**Comment by LiJiahaoCoder** [comment]
谢谢迪哥提醒，我看了一下，好像这个还没有翻译：


| |
李嘉豪
|
|
lijiahao_shandong@163.com
|
签名由网易邮箱大师定制


On 06/18/2020 11:17，ZhangDi<notifications@github.com> wrote：

这个翻译的提交貌似被回滚掉了 @LiJiahaoCoder
