### ISSUE TITLE
react-maintenance - typescript

### ISSUE THREAD

**Issue by LiJiahaoCoder** [the-road-to-learn-react/the-road-to-react-chinese#45]

**Comment by royooooooo** [comment]
I haven't  permission to assign this issue to myself, but I can pick this part.

**Comment by LiJiahaoCoder** [comment]
Hi 付毅，


我之前邀请过你，如图：


请到 GitHub 绑定的邮箱中确认邀请


Best wishes,
Jiahao
| |
李嘉豪
|
|
lijiahao_shandong@163.com
|
签名由网易邮箱大师定制


On 03/30/2020 13:45，Fu Yi<notifications@github.com> wrote：

I haven't permission to assign this issue to myself, but I can pick this part.
